name: Deploy
on:
  push:
	branches: [main]
jobs:
  github-pages:
	runs-on: ubuntu-latest
	steps:
	  - name: Checkout
		uses: actions/checkout@v4.2.0

	  - name: Setup Node.js
		uses: actions/setup-node@v3
		with:
		  node-version: '20'

	  - name: Enable Corepack
		run: corepack enable

	  - name: Install Yarn
		run: corepack prepare yarn@4.5.0 --activate

	  - name: Install Dependencies
		run: yarn install --immutable

	  - name: Build
		run: yarn build:client

	  - name: Deploy to GitHub Pages
		uses: peaceiris/actions-gh-pages@v3
		with:
		  github_token: '${{ secrets.GITHUB_TOKEN }}'
		  publish_dir: ./dist/client
